---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test
  description: This is the description for test
  annotations:
    circleci.com/project-slug: github/sahil-gulati/backstage-demo
    opsgenie.com/component-selector: 'tag:"component:test"'
    backstage.io/techdocs-ref: 'dir:.'
spec:
  type: service
  lifecycle: production
  owner: sahil.gulati1991@outlook.com
