site_name: 'Component documentation'

nav:
  - Home: index.md
  - API:
     Packages: packages.md
     Orders: orders.md
  - Integrations:
     Github: integration/github.md
  

plugins:
  - techdocs-core
  - search
